"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['starter.py']
DATA_FILES = ['start_app.sh','checkin.sh','test.sh', 'checkout.sh', 'test_ui.py']
OPTIONS = {
	'argv_emulation': True,
	'iconfile': './app.icns',
	'packages': ['dotenv', 'tkinter'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
