"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['starter.py']
DATA_FILES = ['checkin.sh','checkout.sh','start_app.sh','status.sh','test_ui.py','test.sh']
OPTIONS = {'argv_emulation': True,'packages': ['dotenv','tkinter']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
